In [35]:
import pandas as pd

In [73]:
students2023 = pd.read_csv("../../../data/bronze/avaliacao_alfabetizacao_2023/DADOS/TS_ALUNO.csv", sep=";", encoding="latin-1")
students2024 = pd.read_csv("../../../data/bronze/avaliacao_alfabetizacao_2024/DADOS/TS_ALUNO.csv", sep=";", encoding="latin-1")
students2025 = pd.read_csv("../../../data/bronze/avaliacao_alfabetizacao_2025/DADOS/TS_ALUNO.csv", sep=";", encoding="latin-1")
all_students = pd.concat([students2023, students2024, students2025], ignore_index=True)

/var/folders/b8/390fxnpd61d49gqxp8n1c7cr0000gq/T/ipykernel_62897/3199241244.py:3: DtypeWarning: Columns (13,14,22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  students2025 = pd.read_csv("../../../data/bronze/avaliacao_alfabetizacao_2025/DADOS/TS_ALUNO.csv", sep=";", encoding="latin-1")

In [74]:
students_columns = {
    'NU_ANO_AVALIACAO': 'year',
    'CO_UF': 'state_code',
    'ID_ALUNO': 'student_id',
    'TP_SERIE': 'grade',
    'ID_ESCOLA': 'school_id',
    'TP_DEPENDENCIA': 'school_administration',
    'CO_MUNICIPIO': 'city_code',
    'IN_PRESENCA_LP': 'student_is_present_exam',
    'VL_PESO_ALUNO_LP': 'student_exam_weight',
    'VL_PROFICIENCIA_LP': 'student_exam_score',
    'IN_ALFABETIZADO': 'student_is_literate',
}

all_students = all_students[list(students_columns.keys())].rename(columns=students_columns)

In [75]:
all_students.head()

,year,state_code,student_id,grade,school_id,school_administration,city_code,student_is_present_exam,student_exam_weight,student_exam_score,student_is_literate
0,2023,11,11008701,2,60000001.0,3.0,1100205.0,0,NaN,NaN,0
1,2023,11,11008695,2,60000001.0,3.0,1100205.0,1,1.045465,714.314857,0
2,2023,11,11008687,2,60000001.0,3.0,1100205.0,0,NaN,NaN,0
3,2023,11,11008682,2,60000001.0,3.0,1100205.0,1,1.045465,759.206313,1
4,2023,11,11008729,2,60000001.0,3.0,1100205.0,0,NaN,NaN,0

In [76]:
cities2023 = pd.read_csv("../../../data/bronze/avaliacao_alfabetizacao_2023/DADOS/TS_MUNICIPIO.csv", sep=";", encoding="latin-1")
cities2024 = pd.read_csv("../../../data/bronze/avaliacao_alfabetizacao_2024/DADOS/TS_MUNICIPIO.csv", sep=";", encoding="latin-1")
cities2025 = pd.read_csv("../../../data/bronze/avaliacao_alfabetizacao_2025/DADOS/TS_MUNICIPIO.csv", sep=";", encoding="latin-1")
all_cities = pd.concat([cities2023, cities2024, cities2025], ignore_index=True)

In [77]:
cities_columns = {
    'NU_ANO_AVALIACAO': 'year',
    'CO_UF': 'state_code',
    'CO_MUNICIPIO': 'city_code',
    'NO_MUNICIPIO': 'city_name',
    'TP_SERIE': 'grade',
    'ID_TIPO_REDE': 'education_network_type',
    'PC_ALUNO_ALFABETIZADO': 'city_percentage_literate_students',
    'VL_MEDIA_LP': 'city_average_exam_score',
}

all_cities = all_cities[list(cities_columns.keys())].rename(columns=cities_columns)

In [78]:
all_cities.head()

,year,state_code,city_code,city_name,grade,education_network_type,city_percentage_literate_students,city_average_exam_score
0,2023,11,1100015,Alta Floresta D'Oeste,2,5,64.55,758.3304
1,2023,11,1100015,Alta Floresta D'Oeste,2,3,64.55,758.3304
2,2023,11,1100023,Ariquemes,2,3,62.30,757.0999
3,2023,11,1100023,Ariquemes,2,5,62.30,757.0999
4,2023,11,1100031,Cabixi,2,5,69.10,767.8763

In [82]:
states2023 = pd.read_csv("../../../data/bronze/avaliacao_alfabetizacao_2023/DADOS/TS_ESTADO.csv", sep=";", encoding="latin-1")
states2024 = pd.read_csv("../../../data/bronze/avaliacao_alfabetizacao_2024/DADOS/TS_ESTADO.csv", sep=";", encoding="latin-1")
states2025 = pd.read_csv("../../../data/bronze/avaliacao_alfabetizacao_2025/DADOS/TS_ESTADO.csv", sep=";", encoding="latin-1")
all_states = pd.concat([states2023, states2024, states2025], ignore_index=True)

In [83]:
states_columns = {
    'NU_ANO_AVALIACAO': 'year',
    'CO_UF': 'state_code',
    'SG_UF': 'state_abbreviation',
    'TP_SERIE': 'grade',
    'ID_TIPO_REDE': 'education_network_type',
    'PC_ALUNO_ALFABETIZADO': 'state_percentage_literate_students',
    'VL_MEDIA_LP': 'state_average_exam_score',
}

all_states = all_states[list(states_columns.keys())].rename(columns=states_columns)

In [84]:
all_states.head()

,year,state_code,state_abbreviation,grade,education_network_type,state_percentage_literate_students,state_average_exam_score
0,2023,11,RO,2,2,58.65,751.4731
1,2023,11,RO,2,3,65.17,760.1971
2,2023,11,RO,2,5,64.60,759.4357
3,2023,13,AM,2,3,49.20,733.6637
4,2023,13,AM,2,5,52.20,736.4687

In [85]:
literate_exam = (
    all_students
    .merge(all_cities,
           how='outer',
           on=['year', 'state_code', 'city_code', 'grade'])
    .merge(all_states,
           how='outer',
           on=['year', 'state_code', 'grade', 'education_network_type'])
)

literate_exam.head()

,year,state_code,student_id,grade,school_id,school_administration,city_code,student_is_present_exam,student_exam_weight,student_exam_score,student_is_literate,city_name,education_network_type,city_percentage_literate_students,city_average_exam_score,state_abbreviation,state_percentage_literate_students,state_average_exam_score
0,2023,11,11002038.0,2,60000162.0,2.0,1100049.0,1.0,1.235294,805.081032,1.0,Cacoal,2.0,66.13,761.9918,RO,58.65,751.4731
1,2023,11,11002030.0,2,60000162.0,2.0,1100049.0,1.0,1.235294,828.128525,1.0,Cacoal,2.0,66.13,761.9918,RO,58.65,751.4731
2,2023,11,11002034.0,2,60000162.0,2.0,1100049.0,1.0,1.235294,828.128525,1.0,Cacoal,2.0,66.13,761.9918,RO,58.65,751.4731
3,2023,11,11002040.0,2,60000162.0,2.0,1100049.0,1.0,1.235294,776.483767,1.0,Cacoal,2.0,66.13,761.9918,RO,58.65,751.4731
4,2023,11,11002045.0,2,60000162.0,2.0,1100049.0,1.0,1.235294,811.093158,1.0,Cacoal,2.0,66.13,761.9918,RO,58.65,751.4731

In [87]:
literate_exam.head(30)

,year,state_code,student_id,grade,school_id,school_administration,city_code,student_is_present_exam,student_exam_weight,student_exam_score,student_is_literate,city_name,education_network_type,city_percentage_literate_students,city_average_exam_score,state_abbreviation,state_percentage_literate_students,state_average_exam_score
0,2023,11,11002038.0,2,60000162.0,2.0,1100049.0,1.0,1.235294,805.081032,1.0,Cacoal,2.0,66.13,761.9918,RO,58.65,751.4731
1,2023,11,11002030.0,2,60000162.0,2.0,1100049.0,1.0,1.235294,828.128525,1.0,Cacoal,2.0,66.13,761.9918,RO,58.65,751.4731
2,2023,11,11002034.0,2,60000162.0,2.0,1100049.0,1.0,1.235294,828.128525,1.0,Cacoal,2.0,66.13,761.9918,RO,58.65,751.4731
3,2023,11,11002040.0,2,60000162.0,2.0,1100049.0,1.0,1.235294,776.483767,1.0,Cacoal,2.0,66.13,761.9918,RO,58.65,751.4731
4,2023,11,11002045.0,2,60000162.0,2.0,1100049.0,1.0,1.235294,811.093158,1.0,Cacoal,2.0,66.13,761.9918,RO,58.65,751.4731
5,2023,11,11002041.0,2,60000162.0,2.0,1100049.0,0.0,NaN,NaN,0.0,Cacoal,2.0,66.13,761.9918,RO,58.65,751.4731
6,2023,11,11002044.0,2,60000162.0,2.0,1100049.0,1.0,1.235294,805.081032,1.0,Cacoal,2.0,66.13,761.9918,RO,58.65,751.4731
7,2023,11,11021400.0,2,60000162.0,2.0,1100049.0,1.0,1.235294,811.093158,1.0,Cacoal,2.0,66.13,761.9918,RO,58.65,751.4731
8,2023,11,11002033.0,2,60000162.0,2.0,1100049.0,1.0,1.235294,805.081032,1.0,Cacoal,2.0,66.13,761.9918,RO,58.65,751.4731
9,2023,11,11002032.0,2,60000162.0,2.0,1100049.0,1.0,1.235294,617.300913,0.0,Cacoal,2.0,66.13,761.9918,RO,58.65,751.4731
10,2023,11,11002031.0,2,60000162.0,2.0,1100049.0,1.0,1.235294,828.128525,1.0,Cacoal,2.0,66.13,761.9918,RO,58.65,751.4731
11,2023,11,11002043.0,2,60000162.0,2.0,1100049.0,0.0,NaN,NaN,0.0,Cacoal,2.0,66.13,761.9918,RO,58.65,751.4731
12,2023,11,11002028.0,2,60000162.0,2.0,1100049.0,0.0,NaN,NaN,0.0,Cacoal,2.0,66.13,761.9918,RO,58.65,751.4731
13,2023,11,11002035.0,2,60000162.0,2.0,1100049.0,1.0,1.235294,828.128525,1.0,Cacoal,2.0,66.13,761.9918,RO,58.65,751.4731
14,2023,11,11002036.0,2,60000162.0,2.0,1100049.0,1.0,1.235294,828.128525,1.0,Cacoal,2.0,66.13,761.9918,RO,58.65,751.4731
15,2023,11,11002042.0,2,60000162.0,2.0,1100049.0,1.0,1.235294,828.128525,1.0,Cacoal,2.0,66.13,761.9918,RO,58.65,751.4731
16,2023,11,11002026.0,2,60000162.0,2.0,1100049.0,1.0,1.235294,828.128525,1.0,Cacoal,2.0,66.13,761.9918,RO,58.65,751.4731
17,2023,11,11002029.0,2,60000162.0,2.0,1100049.0,1.0,1.235294,828.128525,1.0,Cacoal,2.0,66.13,761.9918,RO,58.65,751.4731
18,2023,11,11002039.0,2,60000162.0,2.0,1100049.0,0.0,NaN,NaN,0.0,Cacoal,2.0,66.13,761.9918,RO,58.65,751.4731
19,2023,11,11002027.0,2,60000162.0,2.0,1100049.0,1.0,1.235294,828.128525,1.0,Cacoal,2.0,66.13,761.9918,RO,58.65,751.4731
20,2023,11,11002037.0,2,60000162.0,2.0,1100049.0,1.0,1.235294,756.031279,1.0,Cacoal,2.0,66.13,761.9918,RO,58.65,751.4731
21,2023,11,11002046.0,2,60000163.0,3.0,1100049.0,0.0,NaN,NaN,0.0,Cacoal,2.0,66.13,761.9918,RO,58.65,751.4731
22,2023,11,11002051.0,2,60000163.0,3.0,1100049.0,1.0,1.274355,785.271123,1.0,Cacoal,2.0,66.13,761.9918,RO,58.65,751.4731
23,2023,11,11021402.0,2,60000163.0,3.0,1100049.0,0.0,NaN,NaN,0.0,Cacoal,2.0,66.13,761.9918,RO,58.65,751.4731
24,2023,11,11002055.0,2,60000163.0,3.0,1100049.0,1.0,1.274355,760.304880,1.0,Cacoal,2.0,66.13,761.9918,RO,58.65,751.4731
25,2023,11,11002073.0,2,60000163.0,3.0,1100049.0,1.0,1.274355,717.022836,0.0,Cacoal,2.0,66.13,761.9918,RO,58.65,751.4731
26,2023,11,11002054.0,2,60000163.0,3.0,1100049.0,1.0,1.274355,729.355090,0.0,Cacoal,2.0,66.13,761.9918,RO,58.65,751.4731
27,2023,11,11002057.0,2,60000163.0,3.0,1100049.0,1.0,1.274355,774.948452,1.0,Cacoal,2.0,66.13,761.9918,RO,58.65,751.4731
28,2023,11,11022575.0,2,60000163.0,3.0,1100049.0,1.0,1.274355,757.776563,1.0,Cacoal,2.0,66.13,761.9918,RO,58.65,751.4731
29,2023,11,11002058.0,2,60000163.0,3.0,1100049.0,1.0,1.274355,716.909220,0.0,Cacoal,2.0,66.13,761.9918,RO,58.65,751.4731

In [88]:
literate_exam.tail(40)

,year,state_code,student_id,grade,school_id,school_administration,city_code,student_is_present_exam,student_exam_weight,student_exam_score,student_is_literate,city_name,education_network_type,city_percentage_literate_students,city_average_exam_score,state_abbreviation,state_percentage_literate_students,state_average_exam_score
14941876,2025,53,53067674.0,2,60043396.0,2.0,5300108.0,1.0,1.285714,784.028347,1.0,Brasília,5.0,64.84,747.3454,DF,64.84,747.3454
14941877,2025,53,53067675.0,2,60043592.0,2.0,5300108.0,0.0,NaN,NaN,0.0,Brasília,5.0,64.84,747.3454,DF,64.84,747.3454
14941878,2025,53,53067678.0,2,60043632.0,2.0,5300108.0,1.0,1.117647,765.114048,1.0,Brasília,5.0,64.84,747.3454,DF,64.84,747.3454
14941879,2025,53,53067679.0,2,60043335.0,2.0,5300108.0,0.0,NaN,NaN,0.0,Brasília,5.0,64.84,747.3454,DF,64.84,747.3454
14941880,2025,53,53067680.0,2,60043335.0,2.0,5300108.0,1.0,1.142857,772.169441,1.0,Brasília,5.0,64.84,747.3454,DF,64.84,747.3454
14941881,2025,53,53067683.0,2,60043337.0,2.0,5300108.0,0.0,NaN,NaN,0.0,Brasília,5.0,64.84,747.3454,DF,64.84,747.3454
14941882,2025,53,53067684.0,2,60043337.0,2.0,5300108.0,1.0,1.076923,761.546223,1.0,Brasília,5.0,64.84,747.3454,DF,64.84,747.3454
14941883,2025,53,53067685.0,2,60043338.0,2.0,5300108.0,1.0,1.080000,740.898820,0.0,Brasília,5.0,64.84,747.3454,DF,64.84,747.3454
14941884,2025,53,53067687.0,2,60043340.0,2.0,5300108.0,1.0,1.062500,752.573966,1.0,Brasília,5.0,64.84,747.3454,DF,64.84,747.3454
14941885,2025,53,53067688.0,2,60043340.0,2.0,5300108.0,1.0,1.066667,742.682333,0.0,Brasília,5.0,64.84,747.3454,DF,64.84,747.3454
14941886,2025,53,53067689.0,2,60043342.0,2.0,5300108.0,1.0,1.000000,690.984203,0.0,Brasília,5.0,64.84,747.3454,DF,64.84,747.3454
14941887,2025,53,53067690.0,2,60043342.0,2.0,5300108.0,1.0,1.333333,752.066506,1.0,Brasília,5.0,64.84,747.3454,DF,64.84,747.3454
14941888,2025,53,53067691.0,2,60043342.0,2.0,5300108.0,0.0,NaN,NaN,0.0,Brasília,5.0,64.84,747.3454,DF,64.84,747.3454
14941889,2025,53,53067692.0,2,60043343.0,2.0,5300108.0,1.0,1.166667,780.684610,1.0,Brasília,5.0,64.84,747.3454,DF,64.84,747.3454
14941890,2025,53,53067694.0,2,60043350.0,2.0,5300108.0,1.0,1.176471,773.351431,1.0,Brasília,5.0,64.84,747.3454,DF,64.84,747.3454
14941891,2025,53,53067695.0,2,60043351.0,2.0,5300108.0,1.0,1.750000,743.686164,1.0,Brasília,5.0,64.84,747.3454,DF,64.84,747.3454
14941892,2025,53,53067696.0,2,60043353.0,2.0,5300108.0,1.0,1.222222,709.798489,0.0,Brasília,5.0,64.84,747.3454,DF,64.84,747.3454
14941893,2025,53,53067697.0,2,60043354.0,2.0,5300108.0,1.0,1.300000,762.541661,1.0,Brasília,5.0,64.84,747.3454,DF,64.84,747.3454
14941894,2025,53,53067698.0,2,60043355.0,2.0,5300108.0,1.0,1.208333,745.740244,1.0,Brasília,5.0,64.84,747.3454,DF,64.84,747.3454
14941895,2025,53,53067700.0,2,60043356.0,2.0,5300108.0,1.0,1.071429,783.570332,1.0,Brasília,5.0,64.84,747.3454,DF,64.84,747.3454
14941896,2025,53,53067703.0,2,60043621.0,2.0,5300108.0,1.0,1.363636,679.259927,0.0,Brasília,5.0,64.84,747.3454,DF,64.84,747.3454
14941897,2025,53,53067705.0,2,60043629.0,2.0,5300108.0,1.0,1.062500,825.963411,1.0,Brasília,5.0,64.84,747.3454,DF,64.84,747.3454
14941898,2025,53,53067707.0,2,60043374.0,2.0,5300108.0,1.0,1.176471,752.285921,1.0,Brasília,5.0,64.84,747.3454,DF,64.84,747.3454
14941899,2025,53,53067710.0,2,60043477.0,2.0,5300108.0,0.0,NaN,NaN,0.0,Brasília,5.0,64.84,747.3454,DF,64.84,747.3454
14941900,2025,53,53067720.0,2,60043536.0,2.0,5300108.0,1.0,1.368421,784.309835,1.0,Brasília,5.0,64.84,747.3454,DF,64.84,747.3454
14941901,2025,53,53067723.0,2,60043356.0,2.0,5300108.0,1.0,1.142857,700.274273,0.0,Brasília,5.0,64.84,747.3454,DF,64.84,747.3454
14941902,2025,53,53067731.0,2,60043314.0,2.0,5300108.0,1.0,1.500000,739.671571,0.0,Brasília,5.0,64.84,747.3454,DF,64.84,747.3454
14941903,2025,53,53067732.0,2,60043324.0,2.0,5300108.0,1.0,1.052632,776.552866,1.0,Brasília,5.0,64.84,747.3454,DF,64.84,747.3454
14941904,2025,53,53067735.0,2,60043448.0,2.0,5300108.0,0.0,NaN,NaN,0.0,Brasília,5.0,64.84,747.3454,DF,64.84,747.3454
14941905,2025,53,53067741.0,2,60043433.0,2.0,5300108.0,1.0,1.272727,686.198393,0.0,Brasília,5.0,64.84,747.3454,DF,64.84,747.3454
14941906,2025,53,53067742.0,2,60043435.0,2.0,5300108.0,0.0,NaN,NaN,0.0,Brasília,5.0,64.84,747.3454,DF,64.84,747.3454
14941907,2025,53,53067748.0,2,60043634.0,2.0,5300108.0,0.0,NaN,NaN,0.0,Brasília,5.0,64.84,747.3454,DF,64.84,747.3454
14941908,2025,53,53067750.0,2,60043586.0,2.0,5300108.0,0.0,NaN,NaN,0.0,Brasília,5.0,64.84,747.3454,DF,64.84,747.3454
14941909,2025,53,53067754.0,2,60043528.0,2.0,5300108.0,0.0,NaN,NaN,0.0,Brasília,5.0,64.84,747.3454,DF,64.84,747.3454
14941910,2025,53,53067756.0,2,60043555.0,2.0,5300108.0,1.0,1.357143,692.707529,0.0,Brasília,5.0,64.84,747.3454,DF,64.84,747.3454
14941911,2025,53,53067759.0,2,60043566.0,2.0,5300108.0,1.0,1.000000,796.073218,1.0,Brasília,5.0,64.84,747.3454,DF,64.84,747.3454
14941912,2025,53,53067761.0,2,60043643.0,2.0,5300108.0,1.0,1.315789,765.905079,1.0,Brasília,5.0,64.84,747.3454,DF,64.84,747.3454
14941913,2025,53,53067764.0,2,60043339.0,2.0,5300108.0,1.0,1.052632,720.720275,0.0,Brasília,5.0,64.84,747.3454,DF,64.84,747.3454
14941914,2025,53,53067768.0,2,60043358.0,2.0,5300108.0,0.0,NaN,NaN,0.0,Brasília,5.0,64.84,747.3454,DF,64.84,747.3454
14941915,2025,53,53067771.0,2,60043379.0,2.0,5300108.0,1.0,1.160000,682.243640,0.0,Brasília,5.0,64.84,747.3454,DF,64.84,747.3454

In [89]:
literate_exam.set_index(['student_id', 'year'])

,,state_code,grade,school_id,school_administration,city_code,student_is_present_exam,student_exam_weight,student_exam_score,student_is_literate,city_name,education_network_type,city_percentage_literate_students,city_average_exam_score,state_abbreviation,state_percentage_literate_students,state_average_exam_score
student_id,year,,,,,,,,,,,,,,,,
11002038.0,2023,11,2,60000162.0,2.0,1100049.0,1.0,1.235294,805.081032,1.0,Cacoal,2.0,66.13,761.9918,RO,58.65,751.4731
11002030.0,2023,11,2,60000162.0,2.0,1100049.0,1.0,1.235294,828.128525,1.0,Cacoal,2.0,66.13,761.9918,RO,58.65,751.4731
11002034.0,2023,11,2,60000162.0,2.0,1100049.0,1.0,1.235294,828.128525,1.0,Cacoal,2.0,66.13,761.9918,RO,58.65,751.4731
11002040.0,2023,11,2,60000162.0,2.0,1100049.0,1.0,1.235294,776.483767,1.0,Cacoal,2.0,66.13,761.9918,RO,58.65,751.4731
11002045.0,2023,11,2,60000162.0,2.0,1100049.0,1.0,1.235294,811.093158,1.0,Cacoal,2.0,66.13,761.9918,RO,58.65,751.4731
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53067759.0,2025,53,2,60043566.0,2.0,5300108.0,1.0,1.000000,796.073218,1.0,Brasília,5.0,64.84,747.3454,DF,64.84,747.3454
53067761.0,2025,53,2,60043643.0,2.0,5300108.0,1.0,1.315789,765.905079,1.0,Brasília,5.0,64.84,747.3454,DF,64.84,747.3454
53067764.0,2025,53,2,60043339.0,2.0,5300108.0,1.0,1.052632,720.720275,0.0,Brasília,5.0,64.84,747.3454,DF,64.84,747.3454
53067768.0,2025,53,2,60043358.0,2.0,5300108.0,0.0,NaN,NaN,0.0,Brasília,5.0,64.84,747.3454,DF,64.84,747.3454
53067771.0,2025,53,2,60043379.0,2.0,5300108.0,1.0,1.160000,682.243640,0.0,Brasília,5.0,64.84,747.3454,DF,64.84,747.3454

In [90]:
literate_exam.sort_values(by=['student_id', 'year'], ascending=[True, True], inplace=True)

In [91]:
literate_exam.head(50)

,year,state_code,student_id,grade,school_id,school_administration,city_code,student_is_present_exam,student_exam_weight,student_exam_score,student_is_literate,city_name,education_network_type,city_percentage_literate_students,city_average_exam_score,state_abbreviation,state_percentage_literate_students,state_average_exam_score
12621,2023,11,11000001.0,2,60000062.0,3.0,1100023.0,1.0,1.061728,717.663308,0.0,Ariquemes,3.0,62.30,757.0999,RO,65.17,760.1971
35455,2023,11,11000001.0,2,60000062.0,3.0,1100023.0,1.0,1.061728,717.663308,0.0,Ariquemes,5.0,62.30,757.0999,RO,64.60,759.4357
4187420,2024,11,11000001.0,2,60000062.0,3.0,1100023.0,1.0,1.060000,719.830000,0.0,Ariquemes,3.0,65.62,748.1600,RO,62.56,745.3800
4210093,2024,11,11000001.0,2,60000062.0,3.0,1100023.0,1.0,1.060000,719.830000,0.0,Ariquemes,5.0,65.62,748.1600,RO,62.62,745.5200
12639,2023,11,11000002.0,2,60000062.0,3.0,1100023.0,1.0,1.061728,765.740768,1.0,Ariquemes,3.0,62.30,757.0999,RO,65.17,760.1971
35473,2023,11,11000002.0,2,60000062.0,3.0,1100023.0,1.0,1.061728,765.740768,1.0,Ariquemes,5.0,62.30,757.0999,RO,64.60,759.4357
4187851,2024,11,11000002.0,2,60000062.0,3.0,1100023.0,1.0,1.060000,773.130000,1.0,Ariquemes,3.0,65.62,748.1600,RO,62.56,745.3800
4210524,2024,11,11000002.0,2,60000062.0,3.0,1100023.0,1.0,1.060000,773.130000,1.0,Ariquemes,5.0,65.62,748.1600,RO,62.62,745.5200
12618,2023,11,11000003.0,2,60000062.0,3.0,1100023.0,1.0,1.061728,790.363649,1.0,Ariquemes,3.0,62.30,757.0999,RO,65.17,760.1971
35452,2023,11,11000003.0,2,60000062.0,3.0,1100023.0,1.0,1.061728,790.363649,1.0,Ariquemes,5.0,62.30,757.0999,RO,64.60,759.4357
4187291,2024,11,11000003.0,2,60000062.0,3.0,1100023.0,1.0,1.060000,736.930000,0.0,Ariquemes,3.0,65.62,748.1600,RO,62.56,745.3800
4209964,2024,11,11000003.0,2,60000062.0,3.0,1100023.0,1.0,1.060000,736.930000,0.0,Ariquemes,5.0,65.62,748.1600,RO,62.62,745.5200
12635,2023,11,11000004.0,2,60000062.0,3.0,1100023.0,1.0,1.061728,666.922680,0.0,Ariquemes,3.0,62.30,757.0999,RO,65.17,760.1971
35469,2023,11,11000004.0,2,60000062.0,3.0,1100023.0,1.0,1.061728,666.922680,0.0,Ariquemes,5.0,62.30,757.0999,RO,64.60,759.4357
4187047,2024,11,11000004.0,2,60000062.0,3.0,1100023.0,1.0,1.060000,675.400000,0.0,Ariquemes,3.0,65.62,748.1600,RO,62.56,745.3800
4209720,2024,11,11000004.0,2,60000062.0,3.0,1100023.0,1.0,1.060000,675.400000,0.0,Ariquemes,5.0,65.62,748.1600,RO,62.62,745.5200
12601,2023,11,11000005.0,2,60000062.0,3.0,1100023.0,1.0,1.061728,773.748754,1.0,Ariquemes,3.0,62.30,757.0999,RO,65.17,760.1971
35435,2023,11,11000005.0,2,60000062.0,3.0,1100023.0,1.0,1.061728,773.748754,1.0,Ariquemes,5.0,62.30,757.0999,RO,64.60,759.4357
4187394,2024,11,11000005.0,2,60000062.0,3.0,1100023.0,1.0,1.060000,747.620000,1.0,Ariquemes,3.0,65.62,748.1600,RO,62.56,745.3800
4210067,2024,11,11000005.0,2,60000062.0,3.0,1100023.0,1.0,1.060000,747.620000,1.0,Ariquemes,5.0,65.62,748.1600,RO,62.62,745.5200
12610,2023,11,11000006.0,2,60000062.0,3.0,1100023.0,1.0,1.061728,790.031071,1.0,Ariquemes,3.0,62.30,757.0999,RO,65.17,760.1971
35444,2023,11,11000006.0,2,60000062.0,3.0,1100023.0,1.0,1.061728,790.031071,1.0,Ariquemes,5.0,62.30,757.0999,RO,64.60,759.4357
4186962,2024,11,11000006.0,2,60000062.0,3.0,1100023.0,1.0,1.060000,743.420000,1.0,Ariquemes,3.0,65.62,748.1600,RO,62.56,745.3800
4209635,2024,11,11000006.0,2,60000062.0,3.0,1100023.0,1.0,1.060000,743.420000,1.0,Ariquemes,5.0,65.62,748.1600,RO,62.62,745.5200
12622,2023,11,11000007.0,2,60000062.0,3.0,1100023.0,1.0,1.061728,759.093343,1.0,Ariquemes,3.0,62.30,757.0999,RO,65.17,760.1971
35456,2023,11,11000007.0,2,60000062.0,3.0,1100023.0,1.0,1.061728,759.093343,1.0,Ariquemes,5.0,62.30,757.0999,RO,64.60,759.4357
4187825,2024,11,11000007.0,2,60000062.0,3.0,1100023.0,1.0,1.060000,740.540000,0.0,Ariquemes,3.0,65.62,748.1600,RO,62.56,745.3800
4210498,2024,11,11000007.0,2,60000062.0,3.0,1100023.0,1.0,1.060000,740.540000,0.0,Ariquemes,5.0,65.62,748.1600,RO,62.62,745.5200
12633,2023,11,11000008.0,2,60000062.0,3.0,1100023.0,1.0,1.061728,759.093343,1.0,Ariquemes,3.0,62.30,757.0999,RO,65.17,760.1971
35467,2023,11,11000008.0,2,60000062.0,3.0,1100023.0,1.0,1.061728,759.093343,1.0,Ariquemes,5.0,62.30,757.0999,RO,64.60,759.4357
4187941,2024,11,11000008.0,2,60000062.0,3.0,1100023.0,1.0,1.060000,779.450000,1.0,Ariquemes,3.0,65.62,748.1600,RO,62.56,745.3800
4210614,2024,11,11000008.0,2,60000062.0,3.0,1100023.0,1.0,1.060000,779.450000,1.0,Ariquemes,5.0,65.62,748.1600,RO,62.62,745.5200
12630,2023,11,11000009.0,2,60000062.0,3.0,1100023.0,1.0,1.061728,750.257382,1.0,Ariquemes,3.0,62.30,757.0999,RO,65.17,760.1971
35464,2023,11,11000009.0,2,60000062.0,3.0,1100023.0,1.0,1.061728,750.257382,1.0,Ariquemes,5.0,62.30,757.0999,RO,64.60,759.4357
4187321,2024,11,11000009.0,2,60000062.0,3.0,1100023.0,1.0,1.060000,795.160000,1.0,Ariquemes,3.0,65.62,748.1600,RO,62.56,745.3800
4209994,2024,11,11000009.0,2,60000062.0,3.0,1100023.0,1.0,1.060000,795.160000,1.0,Ariquemes,5.0,65.62,748.1600,RO,62.62,745.5200
12609,2023,11,11000010.0,2,60000062.0,3.0,1100023.0,1.0,1.061728,741.611711,0.0,Ariquemes,3.0,62.30,757.0999,RO,65.17,760.1971
35443,2023,11,11000010.0,2,60000062.0,3.0,1100023.0,1.0,1.061728,741.611711,0.0,Ariquemes,5.0,62.30,757.0999,RO,64.60,759.4357
4187898,2024,11,11000010.0,2,60000062.0,3.0,1100023.0,1.0,1.060000,770.620000,1.0,Ariquemes,3.0,65.62,748.1600,RO,62.56,745.3800
4210571,2024,11,11000010.0,2,60000062.0,3.0,1100023.0,1.0,1.060000,770.620000,1.0,Ariquemes,5.0,65.62,748.1600,RO,62.62,745.5200
12608,2023,11,11000011.0,2,60000062.0,3.0,1100023.0,1.0,1.061728,798.244898,1.0,Ariquemes,3.0,62.30,757.0999,RO,65.17,760.1971
35442,2023,11,11000011.0,2,60000062.0,3.0,1100023.0,1.0,1.061728,798.244898,1.0,Ariquemes,5.0,62.30,757.0999,RO,64.60,759.4357
4186970,2024,11,11000011.0,2,60000062.0,3.0,1100023.0,1.0,1.060000,779.070000,1.0,Ariquemes,3.0,65.62,748.1600,RO,62.56,745.3800
4209643,2024,11,11000011.0,2,60000062.0,3.0,1100023.0,1.0,1.060000,779.070000,1.0,Ariquemes,5.0,65.62,748.1600,RO,62.62,745.5200
12603,2023,11,11000012.0,2,60000062.0,3.0,1100023.0,1.0,1.061728,720.307084,0.0,Ariquemes,3.0,62.30,757.0999,RO,65.17,760.1971
35437,2023,11,11000012.0,2,60000062.0,3.0,1100023.0,1.0,1.061728,720.307084,0.0,Ariquemes,5.0,62.30,757.0999,RO,64.60,759.4357
4187385,2024,11,11000012.0,2,60000062.0,3.0,1100023.0,1.0,1.060000,756.640000,1.0,Ariquemes,3.0,65.62,748.1600,RO,62.56,745.3800
4210058,2024,11,11000012.0,2,60000062.0,3.0,1100023.0,1.0,1.060000,756.640000,1.0,Ariquemes,5.0,65.62,748.1600,RO,62.62,745.5200
12599,2023,11,11000013.0,2,60000062.0,3.0,1100023.0,1.0,1.061728,798.244898,1.0,Ariquemes,3.0,62.30,757.0999,RO,65.17,760.1971
35433,2023,11,11000013.0,2,60000062.0,3.0,1100023.0,1.0,1.061728,798.244898,1.0,Ariquemes,5.0,62.30,757.0999,RO,64.60,759.4357