In [1]:
import pandas as pd

dicionario2023 = pd.read_excel("../../../data/bronze/avaliacao_alfabetizacao_2023/DICIONÁRIO/Dicionario_Microdados_AEEB_2023.xlsx")
dicionario2024 = pd.read_excel("../../../data/bronze/avaliacao_alfabetizacao_2024/DICIONÁRIO/Dicionario_Microdados_AEEB_2024.xlsx")
dicionario2025 = pd.read_excel("../../../data/bronze/avaliacao_alfabetizacao_2025/DICIONÁRIO/Dicionario_Microdados_AEEB_2025.xlsx")

print("Dicionário 2023")
display(dicionario2023.head())

print("Dicionário 2024")
display(dicionario2024.head())

print("Dicionário 2025")
display(dicionario2025)

Dicionário 2023

,TS_ALUNO,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,Nome da Variável,Descrição,Variáveis Categóricas,Tamanho,Tipo
1,NU_ANO_AVALIACAO,Ano de aplicação da avaliação estadual,NaN,4,Numérica
2,CO_UF,Código da Unidade da Federação,NaN,2,Numérica
3,SG_UF,Sigla da Unidade da Federação,NaN,2,Alfanumérica
4,ID_ALUNO,Identificador do Aluno,NaN,8,Numérica

Dicionário 2024

,TS_ALUNO,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,Nome da Variável,Descrição,Variáveis Categóricas,Tamanho,Tipo
1,NU_ANO_AVALIACAO,Ano de aplicação da avaliação estadual,NaN,4,Numérica
2,CO_UF,Código da Unidade da Federação,NaN,2,Numérica
3,SG_UF,Sigla da Unidade da Federação,NaN,2,Alfanumérica
4,ID_ALUNO,Identificador do Aluno,NaN,8,Numérica

Dicionário 2025

,TS_ALUNO,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,Nome da Variável,Descrição,Variáveis Categóricas,Tamanho,Tipo
1,NU_ANO_AVALIACAO,Ano de aplicação da avaliação estadual,NaN,4,Numérica
2,CO_UF,Código da Unidade da Federação,NaN,2,Numérica
3,SG_UF,Sigla da Unidade da Federação,NaN,2,Alfanumérica
4,ID_ALUNO,Identificador do Aluno,NaN,8,Numérica
5,TP_SERIE,Ano Escolar,2 - 2º ano do Ensino Fundamental,1,Numérica
6,ID_ESCOLA,Máscara do Códigoo da Escola (códigos fictícios),NaN,8,Numérica
7,TP_DEPENDENCIA,Dependência Administrativa da Escola,1 - Federal;\n2 - Estadual;\n3 - Municipal;\n4...,1,Numérica
8,CO_MUNICIPIO,Código do Município onde está localizada a esc...,NaN,7,Numérica
9,NO_MUNICIPIO,Nome do Município onde está localizada a escola.,NaN,150,Alfanumérica
10,IN_PRESENCA_LP,Indicador de presença na prova de Língua Portu...,0 - Ausente,1,Numérica
11,NaN,NaN,1 - Presente,NaN,NaN
12,IN_PREENCHIMENTO_LP,Indicador de preenchimento da prova de Língua ...,0 - Prova não preenchida;\n1 - Prova preenchida,1,Numérica
13,CO_CADERNO_LP,Código do Caderno atribuído ao aluno na prova ...,NaN,2,Numérica
14,CO_BLOCO_1,Código do Bloco na posição 1 do Caderno atribu...,NaN,2,Numérica
15,TX_RESPOSTA_BLOCO_1,Vetor com as respostas dos itens objetivos do ...,"A, B, C, D ,E \nX - (item anulado ou abandona...",9,Alfanumérica
16,TX_GABARITO_BLOCO_1,Vetor com o gabarito dos itens objetivos do b...,"A, B, C, D ,E \nX - (item anulado ou abandona...",9,Alfanumérica
17,"CO_BLOCO_2,",Código do Bloco na posição 2 do Caderno atribu...,NaN,2,Numérica
18,TX_RESPOSTA_BLOCO_2,Vetor com as respostas dos itens objetivos do ...,"A, B, C, D ,E \nX - (item anulado ou abandona...",9,Alfanumérica
19,TX_GABARITO_BLOCO_2,Vetor com o gabarito dos itens objetivos do b...,"A, B, C, D ,E \nX - (item anulado ou abandona...",9,Alfanumérica
20,CO_BLOCO_3,Código do Bloco na posição 3 do Caderno atribu...,NaN,2,Numérica
21,TX_RESPOSTA_BLOCO_3,Vetor com as respostas dos itens objetivos do ...,"A, B, C, D ,E \nX - (item anulado ou abandona...",9,Alfanumérica
22,TX_GABARITO_BLOCO_3,Vetor com o gabarito dos itens objetivos do b...,"A, B, C, D ,E \nX - (item anulado ou abandona...",9,Alfanumérica
23,CO_BLOCO_4¹,Código do Bloco na posição 4 do Caderno atribu...,NaN,2,Numérica
24,TX_RESPOSTA_BLOCO_4,Vetor com as respostas dos itens objetivos do ...,"A, B, C, D ,E \nX - (item anulado ou abandona...",9,Alfanumérica
25,TX_GABARITO_BLOCO_4,Vetor com o gabarito dos itens objetivos do b...,"A, B, C, D ,E \nX - (item anulado ou abandona...",9,Alfanumérica
26,VL_PESO_ALUNO_LP,Peso do aluno na prova de Língua Portuguesa,NaN,12,Numérica
27,VL_PROFICIENCIA_LP,Proficiência do aluno em Língua Portuguesa (LP...,NaN,12,Numérica
28,IN_ALFABETIZADO,"Indica se o aluno, mediante o resultado da ava...",0 - Não;\n1 - Sim.,1,Numérica
29,1 - Eventualmente há cadernos com mais de quat...,NaN,NaN,NaN,NaN

In [12]:
alunos2023 = pd.read_csv("../../../data/bronze/avaliacao_alfabetizacao_2023/DADOS/TS_ALUNO.csv", sep=";", encoding="latin-1")
alunos2024 = pd.read_csv("../../../data/bronze/avaliacao_alfabetizacao_2024/DADOS/TS_ALUNO.csv", sep=";", encoding="latin-1")
alunos2025 = pd.read_csv("../../../data/bronze/avaliacao_alfabetizacao_2025/DADOS/TS_ALUNO.csv", sep=";", encoding="latin-1")

print("Alunos 2023")
display(alunos2023.head())

print("Alunos 2024")
display(alunos2024.head())

print("Alunos 2025")
display(alunos2025.head())

/var/folders/b8/390fxnpd61d49gqxp8n1c7cr0000gq/T/ipykernel_9140/387171807.py:3: DtypeWarning: Columns (13,14,22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  alunos2025 = pd.read_csv("../../../data/bronze/avaliacao_alfabetizacao_2025/DADOS/TS_ALUNO.csv", sep=";", encoding="latin-1")

Alunos 2023

,NU_ANO_AVALIACAO,CO_UF,SG_UF,ID_ALUNO,TP_SERIE,ID_ESCOLA,TP_DEPENDENCIA,CO_MUNICIPIO,NO_MUNICIPIO,IN_PRESENCA_LP,IN_PREENCHIMENTO_LP,CO_CADERNO_LP,VL_PESO_ALUNO_LP,VL_PROFICIENCIA_LP,IN_ALFABETIZADO
0,2023,11,RO,11008701,2,60000001,3,1100205,Porto Velho,0,0,17,NaN,NaN,0
1,2023,11,RO,11008695,2,60000001,3,1100205,Porto Velho,1,1,17,1.045465,714.314857,0
2,2023,11,RO,11008687,2,60000001,3,1100205,Porto Velho,0,0,17,NaN,NaN,0
3,2023,11,RO,11008682,2,60000001,3,1100205,Porto Velho,1,1,17,1.045465,759.206313,1
4,2023,11,RO,11008729,2,60000001,3,1100205,Porto Velho,0,0,19,NaN,NaN,0

Alunos 2024

,NU_ANO_AVALIACAO,CO_UF,SG_UF,ID_ALUNO,TP_SERIE,ID_ESCOLA,TP_DEPENDENCIA,CO_MUNICIPIO,NO_MUNICIPIO,IN_PRESENCA_LP,IN_PREENCHIMENTO_LP,CO_CADERNO_LP,VL_PESO_ALUNO_LP,VL_PROFICIENCIA_LP,IN_ALFABETIZADO
0,2024,11,RO,11022231,2,60000163,3,1100015,Alta Floresta D'Oeste,1,1,1,1.06,759.43,1
1,2024,11,RO,11019498,2,60000164,3,1100015,Alta Floresta D'Oeste,1,1,10,1.00,741.28,0
2,2024,11,RO,11019621,2,60000334,3,1100015,Alta Floresta D'Oeste,1,1,9,1.13,807.04,1
3,2024,11,RO,11019638,2,60000334,3,1100015,Alta Floresta D'Oeste,1,1,19,1.09,730.96,0
4,2024,11,RO,11019694,2,60000379,3,1100015,Alta Floresta D'Oeste,1,1,8,1.11,735.46,0

Alunos 2025

,NU_ANO_AVALIACAO,CO_UF,SG_UF,ID_ALUNO,TP_SERIE,ID_ESCOLA,TP_DEPENDENCIA,CO_MUNICIPIO,NO_MUNICIPIO,IN_PRESENCA_LP,...,TX_GABARITO_BLOCO_2,CO_BLOCO_3,TX_RESPOSTA_BLOCO_3,TX_GABARITO_BLOCO_3,CO_BLOCO_4,TX_RESPOSTA_BLOCO_4,TX_GABARITO_BLOCO_4,VL_PESO_ALUNO_LP,VL_PROFICIENCIA_LP,IN_ALFABETIZADO
0,2025,11,RO,11000677,2,60000060.0,3.0,1100023.0,Ariquemes,1,...,BADA,6.0,BBCD,ABCB,NaN,NaN,NaN,1.5,781.776332,1
1,2025,11,RO,11000678,2,60000060.0,3.0,1100023.0,Ariquemes,1,...,BADA,6.0,DACB,ABCB,NaN,NaN,NaN,1.5,717.877346,0
2,2025,11,RO,11000679,2,60000060.0,3.0,1100023.0,Ariquemes,1,...,ABDA,7.0,BBBB,ABBD,NaN,NaN,NaN,1.5,657.836805,0
3,2025,11,RO,11000680,2,60000060.0,3.0,1100023.0,Ariquemes,1,...,BACB,5.0,CABA,ABDA,NaN,NaN,NaN,1.5,765.290294,1
4,2025,11,RO,11000681,2,60000060.0,3.0,1100023.0,Ariquemes,1,...,ABCB,8.0,CABA,CABA,NaN,NaN,NaN,1.5,835.506362,1

In [17]:
alunos2023.query("NO_MUNICIPIO == 'Águas Lindas de Goiás'")

,NU_ANO_AVALIACAO,CO_UF,SG_UF,ID_ALUNO,TP_SERIE,ID_ESCOLA,TP_DEPENDENCIA,CO_MUNICIPIO,NO_MUNICIPIO,IN_PRESENCA_LP,IN_PREENCHIMENTO_LP,CO_CADERNO_LP,VL_PESO_ALUNO_LP,VL_PROFICIENCIA_LP,IN_ALFABETIZADO
1696638,2023,52,GO,52073809,2,60042053,3,5200258,Águas Lindas de Goiás,1,1,19,1.593493,707.742739,0
1696639,2023,52,GO,52073833,2,60042053,3,5200258,Águas Lindas de Goiás,1,1,20,1.156321,735.150112,0
1696640,2023,52,GO,52073825,2,60042053,3,5200258,Águas Lindas de Goiás,1,1,20,1.156321,664.762199,0
1696641,2023,52,GO,52073829,2,60042053,3,5200258,Águas Lindas de Goiás,1,1,20,1.156321,736.634235,0
1696642,2023,52,GO,52082256,2,60042053,3,5200258,Águas Lindas de Goiás,1,1,20,1.156321,684.133871,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1747434,2023,52,GO,52076808,2,60042811,3,5200258,Águas Lindas de Goiás,1,1,6,1.341165,721.771196,0
1747435,2023,52,GO,52076800,2,60042811,3,5200258,Águas Lindas de Goiás,1,1,6,1.341165,762.068013,1
1747436,2023,52,GO,52076799,2,60042811,3,5200258,Águas Lindas de Goiás,0,0,6,NaN,NaN,0
1747437,2023,52,GO,52076782,2,60042811,3,5200258,Águas Lindas de Goiás,0,0,6,NaN,NaN,0
1747438,2023,52,GO,52076854,2,60042811,3,5200258,Águas Lindas de Goiás,1,1,1,1.364304,735.200207,0

In [4]:


censo2025 = pd.read_csv("../../../microdados_censo_escolar_2025_v2/dados/Tabela_Matricula_2025_V2.csv", sep=";", encoding="latin-1")

print("Censo Escolar 2025")
display(censo2025.head())

/var/folders/b8/390fxnpd61d49gqxp8n1c7cr0000gq/T/ipykernel_23649/3716219099.py:1: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  censo2025 = pd.read_csv("../../../microdados_censo_escolar_2025_v2/dados/Tabela_Matricula_2025_V2.csv", sep=";", encoding="latin-1")

Censo Escolar 2025

,NU_ANO_CENSO,NO_REGIAO,CO_REGIAO,NO_UF,SG_UF,CO_UF,NO_MUNICIPIO,CO_MUNICIPIO,NO_REGIAO_GEOG_INTERM,CO_REGIAO_GEOG_INTERM,...,QT_MAT_ESP_INT,QT_MAT_ESP_CC_INT,QT_MAT_ESP_CE_INT,QT_MAT_BAS_LIBRAS,QT_MAT_ZR_URB,QT_MAT_ZR_RUR,QT_MAT_ZR_NA,QT_TRANSP_PUBLICO,QT_TRANSP_RESP_EST,QT_TRANSP_RESP_MUN
0,2025,Norte,1,Rondônia,RO,11,Alta Floresta D'Oeste,1100015,Ji-Paraná,1102.0,...,0,0,0,0,0,4,0,0,0,0
1,2025,Norte,1,Rondônia,RO,11,Alta Floresta D'Oeste,1100015,Ji-Paraná,1102.0,...,0,0,0,0,81,27,0,0,0,0
2,2025,Norte,1,Rondônia,RO,11,Alta Floresta D'Oeste,1100015,Ji-Paraná,1102.0,...,0,0,0,0,3,161,0,130,0,130
3,2025,Norte,1,Rondônia,RO,11,Alta Floresta D'Oeste,1100015,Ji-Paraná,1102.0,...,11,11,0,0,253,303,0,258,0,258
4,2025,Norte,1,Rondônia,RO,11,Alta Floresta D'Oeste,1100015,Ji-Paraná,1102.0,...,0,0,0,0,0,60,0,53,0,53